export {default as  NotFound} from './404'
export {default as  Home} from './Home'
export {default as  Profile} from './Profile'
export {default as  Login} from './login'
export {default as  PostPage} from './Post'
